import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Splash & Landing
    'splash.title': 'Diamond Solution',
    'splash.subtitle': 'Institutional Academic Excellence',
    'splash.tagline': '"Empowering students across West Africa to achieve academic excellence — one question at a time."',
    'splash.departments': 'Departments',
    'splash.questions': 'Questions',
    'splash.commission': 'Commission',
    'splash.initiate': 'Initiate Academic Journey',
    'splash.signin': 'Sign In to Repository',
    'splash.professional': 'Professional • Secured • Institutionalized',
    
    // Auth
    'auth.login': 'Access Terminal',
    'auth.email': 'Institutional Email',
    'auth.password': 'Password',
    'auth.signin': 'Authorize Access',
    'auth.noAccount': 'Need clearance? Register with Registrar',
    'auth.forgotPassword': 'Reset Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.resetSent': 'Reset Protocol Initiated. Check Email.',
    'auth.verifyEmail': 'Security Verification Required',
    'auth.otpSent': 'OTP code dispatched to your institutional email.',
    
    // Navigation
    'nav.home': 'Dashboard',
    'nav.study': 'Departments',
    'nav.affiliate': 'Affiliates',
    'nav.profile': 'User',
    'nav.chat': 'Chats',
    'nav.support': 'Technical Support',
    'nav.admin': 'Admin',
    'nav.notifications': 'Intelligence',
    'nav.logout': 'Terminate Session',
    
    // Dashboard
    'dashboard.welcome': 'Institutional Dashboard',
    'dashboard.study': 'Knowledge Repository',
    'dashboard.profile': 'User',
    'dashboard.notifications': 'Signal Intelligence',
    'dashboard.recent': 'Recent Activity',
    'dashboard.wisdom': 'Wisdom of the Day',
    'dashboard.goal': 'Daily Practice Goal',
    'dashboard.refer_earn': 'Refer & Earn 25%',
    'dashboard.refer_sub': 'Share your institutional code and earn on every successful enrollment.',
    'dashboard.progress': 'Operational Progress',
    'dashboard.stats': 'Efficiency Metrics',
    'dashboard.inactivity': 'Inactivity Protocol',
    'dashboard.study_limit': 'Days since last session',
    'dashboard.question_goal': 'Monthly Goal Progress (50+ qns)',
    
    // Study / Course List
    'study.browse': 'Browse Archives',
    'study.filter': 'Filter Repository',
    'study.level': 'Academic Level',
    'study.category': 'Classification',
    'study.no_courses': 'No records found in this vector.',
    'study.unlock': 'Unlock Protocol',
    'study.course_detail': 'File Specification',
    'study.start_quiz': 'Initiate Assessment',
    'study.resume': 'Resume Protocol',
    
    // Course List / Faculties
    'courses.faculties': 'Institutional Departments',
    'courses.archives': 'Departments of Global Excellence',
    'courses.faculty': 'Institutional Department',
    'courses.restricted': 'Archives Restricted',
    'courses.restrictionDesc': 'To view levels and access examination repositories for this faculty, institutional authorization is required.',
    'courses.authorized': 'Access Authorized',
    'courses.required': 'Authorization Required',
    'courses.back': 'Global Archives',
    'courses.levels': 'Levels',
    'courses.fee': 'Full Faculty Fee',
    'courses.payAccess': 'Pay {price} for Full Access',
    'courses.oneTime': 'One-time protocol. Recursive access granted.',
    'courses.searchPlaceholder': 'Search archives...',
    'courses.noRecords': 'No matching records in this faculty.',
    
    // Study Page / Quiz
    'study.noContent': 'No content synchronization found',
    'study.noContentDesc': 'Archival board is currently populating this session.',
    'study.concluded': 'Session Concluded',
    'study.resultCard': 'Official Result Card',
    'study.compliance': 'Compliance',
    'study.resync': 'Re-Sync',
    'study.exit': 'Exit',
    'study.linguisticSync': 'Linguistic Sync...',
    'study.questionStatus': 'Question {n} of {m}',
    'study.protocolStatus': 'Protocol Status',
    'study.synthesisComplete': 'Synthesis Complete',
    'study.awaitingSelection': 'Awaiting Selection',
    'study.commitSolution': 'Commit Solution',
    'study.concludeSession': 'Conclude Academic Session',
    'study.nextQuery': 'Proceed to Next Query',
    'study.archiveQuery': 'Archive Query',
    'study.institutionalSynthesis': 'Institutional Synthesis',
    
    // Course Detail
    'course.notFound': 'Scholastic record not found',
    'course.level': 'Level',
    'course.status': 'Status',
    'course.institutional': 'Institutional',
    'course.security': 'Security',
    'course.encrypted': 'Encrypted',
    'course.endowment': 'Endowment',
    'course.yield': '25% Yield',
    'course.paymentTags': 'Lifetime Access • One-time Payment • Secured Transaction',
    'course.objectives': 'Academic Objectives',
    'course.obj1': 'Mastery of critical forensic exam analysis',
    'course.obj2': 'Advanced theoretical foundations',
    'course.obj3': 'Comprehensive understanding of regional board patterns',
    'course.obj4': 'Synchronous archival access via digital terminals',
    'course.initiate_protocol': 'Initiate Protocol',
    
    // Profile
    'profile.defaultName': 'Academic Partner',
    'profile.defaultRole': 'Verified Student',
    'profile.verification': 'Institutional Verification',
    'profile.institution': 'Affiliated Institution',
    'profile.awaiting': 'Awaiting Verification',
    'profile.contact': 'Protocol Contact',
    'profile.notConfigured': 'Not Configured',
    'profile.settings': 'Institutional Settings',
    'profile.notifications': 'Notification Center',
    'profile.activityLog': 'Revision & Activity Logs',
    'profile.account': 'Account Settings',
    'profile.partnerProgram': 'Partner Program',
    'profile.affiliateRepo': 'Affiliate Repository',
    'profile.support': 'Technical Support',
    'profile.admin': 'System Administration',
    'profile.requestAdmin': 'Request Admin Privileges',
    'profile.adminRequested': 'Admin request dispatched to central authority.',
    'profile.current_password': 'Current Password',
    'profile.new_password': 'New Password',
    
    // Quiz/Study Page
    'quiz.question': 'Query',
    'quiz.explanation': 'Analytical Briefing',
    'quiz.submit': 'Submit Response',
    'quiz.next': 'Next Query',
    'quiz.finish': 'Finalize Assessment',
    'quiz.results': 'Operational Output',
    'quiz.score': 'Performance Score',
    'quiz.correct': 'Accurate',
    'quiz.wrong': 'Inaccurate',
    'quiz.time': 'Temporal Duration',
    
    // Affiliate
    'affiliate.title': 'Partner Terminal',
    'affiliate.balance': 'Commission Credit',
    'affiliate.referrals': 'Recruited Assets',
    'affiliate.withdraw': 'Request Disbursement',
    'affiliate.code': 'Referral Identifier',
    'affiliate.copy': 'Copy ID',
    'affiliate.history': 'Disbursement Log',
    
    // Affiliate Dashboard Expanded
    'affiliate.subtitle': 'Institutional Growth & Revenue Shares',
    'affiliate.syncing_account': 'Synchronizing Affiliate Account',
    'affiliate.syncing_desc': 'Initial engagement detected. Provisioning your unique Diamond Partner credentials...',
    'affiliate.activation_required': 'Activation Required',
    'affiliate.activation_desc': 'Join the institutional partner program to generate your referral credentials and start earning.',
    'affiliate.awaiting_auth': 'Awaiting Authorization',
    'affiliate.awaiting_desc': 'Our admins are currently verifying your institutional status. This protocol usually completes within 24 standard hours.',
    'affiliate.fee': 'Commitment Fee',
    'affiliate.yield': 'Yield share',
    'affiliate.execute_activation': 'Execute Activation Protocol',
    'affiliate.endowment': 'Withdrawable Endowment',
    'affiliate.place_withdrawal': 'Place Withdrawal',
    'affiliate.payout_creds': 'Institutional Payout Credentials',
    'affiliate.update_authority': 'Update Authority',
    'affiliate.init_creds': 'Initialize Credentials',
    'affiliate.bank_hierarchy': 'Bank Hierarchy',
    'affiliate.access_id': 'Access Identifier',
    'affiliate.authorize_bank_desc': 'Authorize your institutional bank account to enable revenue redistribution.',
    'affiliate.your_id': 'Your Institutional Identifier',
    'affiliate.sync_cache': 'Identifier Synchronized to Cache',
    'affiliate.referred_assets': 'Referred Assets',
    'affiliate.total_earned': 'Total Earned',
    'affiliate.rev_share': 'Revenue Share',
    'affiliate.net_balance': 'Net Balance',
    'affiliate.commission_archives': 'Commission Archives',
    'affiliate.enrollment': 'Enrollment',
    'affiliate.direct_referral': 'Direct Referral',
    'affiliate.awaiting_endowment': 'Awaiting your first institutional endowment',
    'affiliate.redistributions': 'Revenue Redistributions',
    'affiliate.no_redistributed': 'No redistributed revenue found in archives',
    'affiliate.network_sync': 'Network Synchronization',
    'affiliate.verified_user': 'Verified Institutional User',
    'affiliate.active': 'Active',
    'affiliate.awaiting_network': 'Awaiting Network Expansion...',
    'affiliate.payout_authority': 'Institutional Payout Authority',
    'affiliate.sync_creds_desc': 'Synchronize your bank credentials for redistribution',
    'affiliate.financial_institution': 'Financial Institution',
    'affiliate.select_hub': 'Select Institutional Hub',
    'affiliate.acc_no': 'Access Identifier (Account No)',
    'affiliate.beneficiary': 'Legal Beneficiary Name',
    'affiliate.authorize_creds': 'Authorize Credentials',
    
    // Chat
    'chat.title': 'Institutional Support',
    'chat.boardOnline': 'Archival Board Online',
    'chat.security': 'Security: Triple-Layer 256B',
    'chat.channelEstablished': 'Secure Channel Established',
    'chat.queriesSync': 'Institutional queries are synchronized here.',
    'chat.senderAdmin': 'ArchBoard',
    'chat.placeholder': 'Query institutional support...',
    
    // Admin Dashboard
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.practice': 'Daily Practice',
    'admin.affiliates': 'Affiliates',
    'admin.withdrawals': 'Withdrawals',
    'admin.payments': 'Payments',
    'admin.analytics': 'Analytics',
    'admin.departments': 'Departments',
    'admin.questions': 'Questions',
    'admin.notifications': 'Notifications',
    'admin.quotes': 'Quotes',
    'admin.support': 'Support',
    'admin.settings': 'Settings',
    'admin.main': 'Main',
    'admin.finance': 'Finance',
    'admin.content': 'Content',
    'admin.superAdmin': 'Super Admin',
    'admin.broadcastProtocol': 'Broadcast Protocol',
    'admin.refreshArchives': 'Refresh Archives',
    'admin.overview': 'Overview',
    'admin.totalRevenue': 'Total Revenue',
    'admin.totalPaidOut': 'Total Paid Out',
    'admin.totalStudents': 'Total Students',
    'admin.pendingAffiliates': 'Pending Affiliates',
    'admin.pendingPayouts': 'Pending Payouts',
    'admin.recentPayments': 'Recent Payments',
    'admin.viewLedger': 'View Ledger',
    'admin.revenueBreakdown': 'Revenue Breakdown',
    'admin.scholarProfile': 'Scholar Profile',
    'admin.referrer': 'Referrer',
    'admin.institutionalDept': 'Institutional Dept',
    'admin.affiliateStatus': 'Affiliate Status',
    'admin.approvePartner': 'Approve Partner',
    'admin.role': 'Role',
    'admin.status': 'Status',
    'admin.actions': 'Actions',
    'admin.export': 'Export',
    'admin.addUser': 'Add User',
    'admin.protocolActive': 'Global Protocol Active',
    'admin.matrix': 'Matrix',
    'admin.registry': 'Registry',
    'admin.pendingActivations': 'Pending Activations',
    'admin.partnerRegistry': 'Partner Registry',
    'admin.refCode': 'Referral Code',
    'admin.totalEarned': 'Total Earned',
    'admin.totalPaid': 'Total Paid',
    'admin.balance': 'Balance',
    'admin.searchTransaction': 'Search transaction reference...',
    'admin.protocolRef': 'Protocol Ref',
    'admin.scholarlyPayer': 'Scholarly Payer',
    'admin.endowment': 'Endowment',
    'admin.timestamp': 'Timestamp',
    'admin.revenueHistory': 'Revenue History (Annual)',
    'admin.payoutHistory': 'Affiliate Payouts (Annual)',
    'admin.manifestFaculty': 'Manifest New Department',
    'admin.addFaculty': 'Manifest New Department',
    'admin.facultyName': 'Institutional Name',
    'admin.systemSlug': 'System Slug',
    'admin.tuitionBase': 'Tuition Base',
    'admin.operationalMode': 'Operational Mode',
    'admin.defaultInstitutional': 'Default Institutional',
    'admin.adminCustomized': 'Admin Customized',
    'admin.archives': 'Edit Archives',
    'admin.editArchives': 'Edit Archives',
    'admin.updateFee': 'Update Fee',
    'admin.modifyFaculty': 'Update Department Archive',
    'admin.initializeFaculty': 'Department Manifestation',
    'admin.tuitionFee': 'Tuition',
    'admin.authorizeFaculty': 'Authorize Department',
    'admin.authorizeUpdate': 'Authorize Update',
    'admin.publishUpdates': 'Publish Updates',
    'admin.initializeProtocol': 'Initialize Protocol',
    'admin.facultySecurityClearance': 'Department Security Clearance',
    'admin.verificationCodeSent': 'Enter the 6-digit one-time token sent to',
    'admin.authorizeProtocol': 'Authorize Action',
    'admin.abortLaunch': 'Abort',
    'admin.allDepts': 'All Departments',
    'admin.downloadTemplate': 'Download Template',
    'admin.importArchive': 'Import Archive',
    'admin.exportArchive': 'Export Archive',
    'admin.addNewQuestion': 'Add New Question (Ask)',
    'admin.selectDepartment': 'Select Department Faculty',
    'admin.chooseAnArchive': 'Choose an archive from the navigation bar above to begin scholarly maintenance.',
    'admin.selectArchive': 'Select an archive to begin processing',
    'admin.createNewArchive': 'Create New Archive',
    'admin.confirmDestruction': 'Confirm Destruction',
    'admin.courseDeleteWarning': 'This will permanently erase the entire archive and all its associated queries from the database.',
    'admin.questionDeleteWarning': 'Are you sure you want to erase this specific query? This action cannot be undone.',
    'admin.archiveProvisioning': 'Archive Provisioning',
    'admin.archiveTitle': 'Archive Title',
    'admin.faculty': 'Department',
    'admin.level': 'Level',
    'admin.executeProvisioning': 'Execute Provisioning',
    'admin.modifyQuestion': 'Revise Archive Query',
    'admin.protocolSync': 'Institutional examination logic synchronization',
    'admin.autoTranslate': 'Auto-Translate to French',
    'admin.examinationQuery': 'Examination Query',
    'admin.responseOptions': 'Response Options',
    'admin.rationalExplanation': 'Rational Explanation',
    'admin.explanation': 'Explanation',
    'admin.logRevisions': 'Log Revisions',
    'admin.syncArchives': 'Sync to Archives',
    'admin.broadcastSystem': 'Scholarly Broadcast System',
    'admin.dispatchGlobal': 'Dispatch global system announcements and updates to all users.',
    'admin.notificationTitle': 'Notification Title',
    'admin.notificationContent': 'Announcement Content',
    'admin.type': 'Type',
    'admin.critical': 'Critical',
    'admin.info': 'Info',
    'admin.success': 'Success',
    'admin.warning': 'Warning',
    'admin.broadcast': 'Broadcast',
    'admin.activeBulletins': 'Active Bulletins',
    'admin.issuedBy': 'Issued By',
    'admin.motivationalArchives': 'Motivational Archives',
    'admin.addOracle': 'Add Oracle Wisdom',
    'admin.quoteText': 'Wisdom Text',
    'admin.author': 'Author',
    'admin.resolutionTerminal': 'Issue Resolution Terminal',
    'admin.openTickets': 'Open Tickets',
    'admin.resolvedTickets': 'Resolved Archive',
    'admin.resolveTicket': 'Resolve Ticket',
    'admin.abort': 'Abort',
    'admin.delete': 'Delete',
    'admin.confirmationDestruction': 'Confirm Destruction',
    'admin.initiateTransmission': 'Initiate Transmission',
    'admin.protocolHeader': 'Protocol Header (Title)',
    'admin.payload': 'Transmission Payload (Body)',
    'admin.broadcastSecure': 'Broadcast Secure Protocol',
    'admin.historyLog': 'Transmission History Log',
    'admin.mentalFramework': 'Log Mental Framework',
    'admin.epistemological': 'Epistemological Text',
    'admin.intellectualOrigin': 'Intellectual Origin (Author)',
    'admin.publish': 'Authenticate & Publish',
    'admin.activeThreads': 'Active Threads',
    'admin.secureSession': 'Secure session initialized',
    
    // General / UI
    'general.back': 'Withdraw',
    'general.submit': 'Submit Clearance',
    'general.loading': 'Processing Data...',
    'general.error': 'System Error',
    'general.success': 'Operation Successful',
    'general.cancel': 'Abort',
    'general.save': 'Commit Changes',
    'general.edit': 'Modify',
    'general.delete': 'Purge',
    'general.view': 'Inspect',
    'general.search': 'Execute Query...',
    
    // Payments
    'payment.authorize': 'Authorize Payment',
    'payment.currency': 'NGN',
    'payment.intl_currency': 'USD',
    'payment.unlocked': 'Access Granted',
    'payment.locked': 'Access Required',
    'payment.pay_now': 'Authorize Transaction',
    
    // Access
    'access.restricted': 'Access Restricted',
    'access.restricted_desc': 'The archives for this faculty require institutional authorization.',
    'access.provision': 'Provision Access Terminal',
    
    // Greetings
    'greet.morning': 'Good morning',
    'greet.afternoon': 'Good afternoon',
    'greet.evening': 'Good evening',
    
    // Stats
    'stats.attempted': 'Attempted',
    'stats.avg_score': 'Avg Score',
    'stats.correct': 'Correct',
    'stats.streak': 'Day Streak',
    
    // Actions - Quick
    'actions.study_now': 'Study Now',
    'actions.support_admin': 'Talk to Admin',
    
    // Departments (Mappings)
    'dept.Pharmacy': 'Pharmacy',
    'dept.Physiotherapy': 'Physiotherapy',
    'dept.Biomedical Laboratory Science (BMLS)': 'Biomedical Laboratory Science (BMLS)',
    'dept.Medicine and Surgery (MBBS)': 'Medicine and Surgery (MBBS)',
    'dept.Nursing': 'Nursing'
  },
  fr: {
    // Splash & Landing
    'splash.title': 'Solution Diamant',
    'splash.subtitle': 'Excellence Académique Institutionnelle',
    'splash.tagline': '"Autonomiser les étudiants à travers l\'Afrique de l\'Ouest pour atteindre l\'excellence académique — une question à la fois."',
    'splash.departments': 'Départements',
    'splash.questions': 'Questions',
    'splash.commission': 'Commission',
    'splash.initiate': 'Initier un Parcours Académique',
    'splash.signin': 'Se connecter au Dépôt',
    'splash.professional': 'Professionnel • Sécurisé • Institutionnalisé',
    
    // Auth
    'auth.login': 'Terminal d\'Accès',
    'auth.email': 'Email Institutionnel',
    'auth.password': 'Mot de Passe',
    'auth.signin': 'Autoriser l\'Accès',
    'auth.noAccount': 'Besoin d\'autorisation? S\'inscrire au Registre',
    'auth.forgotPassword': 'Réinitialiser le Mot de Passe',
    'auth.confirmPassword': 'Confirmer le Mot de Passe',
    'auth.resetSent': 'Protocole de Réinitialisation Initié. Vérifiez vos Emails.',
    'auth.verifyEmail': 'Vérification de Sécurité Requise',
    'auth.otpSent': 'Code OTP envoyé à votre email institutionnel.',
    
    // Navigation
    'nav.home': 'Dashboard',
    'nav.study': 'Départements',
    'nav.affiliate': 'Affiliés',
    'nav.profile': 'Utilisateur',
    'nav.chat': 'Chats',
    'nav.support': 'Support Technique',
    'nav.admin': 'Admin',
    'nav.notifications': 'Intelligence',
    'nav.logout': 'Terminer la Session',
    
    // Dashboard
    'dashboard.welcome': 'Tableau de Bord Institutionnel',
    'dashboard.study': 'Dépôt de Connaissances',
    'dashboard.profile': 'Utilisateur',
    'dashboard.notifications': 'Intelligence de Signal',
    'dashboard.recent': 'Activité Récente',
    'dashboard.wisdom': 'Sagesse du Jour',
    'dashboard.goal': 'Objectif de Pratique Quotidienne',
    'dashboard.refer_earn': 'Parrainez et Gagnez 25%',
    'dashboard.refer_sub': 'Partagez votre code institutionnel et gagnez sur chaque inscription réussie.',
    'dashboard.progress': 'Progrès Opérationnel',
    'dashboard.stats': 'Mesures d\'Efficacité',
    'dashboard.inactivity': 'Protocole d\'Inactivité',
    'dashboard.study_limit': 'Jours depuis la dernière session',
    'dashboard.question_goal': 'Objectif Mensuel (50+ qns)',
    
    // Study / Course List
    'study.browse': 'Parcourir les Archives',
    'study.filter': 'Filtrer le Dépôt',
    'study.level': 'Niveau Académique',
    'study.category': 'Classification',
    'study.no_courses': 'Aucun enregistrement trouvé dans ce vecteur.',
    'study.unlock': 'Protocole de Déverrouillage',
    'study.course_detail': 'Spécification du Fichier',
    'study.start_quiz': 'Initier l\'Évaluation',
    'study.resume': 'Reprendre le Protocole',
    
    // Course List / Faculties
    'courses.faculties': 'Départements Institutionnels',
    'courses.archives': 'Départements de l\'Excellence Globale',
    'courses.faculty': 'Département Institutionnel',
    'courses.restricted': 'Archives Restreintes',
    'courses.restrictionDesc': 'Pour consulter les niveaux et accéder aux dépôts d\'examens de cette faculté, une autorisation institutionnelle est requise.',
    'courses.authorized': 'Accès Autorisé',
    'courses.required': 'Autorisation Requise',
    'courses.back': 'Archives Globales',
    'courses.levels': 'Niveaux',
    'courses.fee': 'Frais de Faculté Complets',
    'courses.payAccess': 'Payer {price} pour un Accès Complet',
    'courses.oneTime': 'Protocole unique. Accès récursif accordé.',
    'courses.searchPlaceholder': 'Rechercher dans les archives...',
    'courses.noRecords': 'Aucun enregistrement correspondant dans cette faculté.',
    
    // Study Page / Quiz
    'study.noContent': 'Aucune synchronisation de contenu trouvée',
    'study.noContentDesc': 'Le conseil des archives alimente actuellement cette session.',
    'study.concluded': 'Session Conclue',
    'study.resultCard': 'Fiche de Résultat Officielle',
    'study.compliance': 'Conformité',
    'study.resync': 'Ré-Synchroniser',
    'study.exit': 'Quitter',
    'study.linguisticSync': 'Synchronisation Linguistique...',
    'study.questionStatus': 'Question {n} de {m}',
    'study.protocolStatus': 'Statut du Protocole',
    'study.synthesisComplete': 'Synthèse Terminée',
    'study.awaitingSelection': 'En Attente de Sélection',
    'study.commitSolution': 'Commiter la Solution',
    'study.concludeSession': 'Conclure la Session Académique',
    'study.nextQuery': 'Passer à la Requête Suivante',
    'study.archiveQuery': 'Requête d\'Archivage',
    'study.institutionalSynthesis': 'Synthèse Institutionnelle',
    
    // Course Detail
    'course.notFound': 'Enregistrement scolaire introuvable',
    'course.level': 'Niveau',
    'course.status': 'Statut',
    'course.institutional': 'Institutionnel',
    'course.security': 'Sécurité',
    'course.encrypted': 'Chiffré',
    'course.endowment': 'Dotation',
    'course.yield': 'Rendement de 25%',
    'course.paymentTags': 'Accès à Vie • Paiement Unique • Transaction Sécurisée',
    'course.objectives': 'Objectifs Académiques',
    'course.obj1': 'Maîtrise de l\'analyse critique des examens médico-légaux',
    'course.obj2': 'Fondements théoriques avancés',
    'course.obj3': 'Compréhension globale des schémas des conseils régionaux',
    'course.obj4': 'Accès aux archives synchrones via terminaux numériques',
    'course.initiate_protocol': 'Initier le Protocole',
    
    // Profile
    'profile.defaultName': 'Partenaire Académique',
    'profile.defaultRole': 'Étudiant Vérifié',
    'profile.verification': 'Vérification Institutionnelle',
    'profile.institution': 'Institution Affiliée',
    'profile.awaiting': 'En Attente de Vérification',
    'profile.contact': 'Contact de Protocole',
    'profile.notConfigured': 'Non Configuré',
    'profile.settings': 'Paramètres Institutionnels',
    'profile.notifications': 'Centre de Notifications',
    'profile.activityLog': 'Journaux de Révision et d\'Activité',
    'profile.account': 'Paramètres du Compte',
    'profile.partnerProgram': 'Programme de Partenariat',
    'profile.affiliateRepo': 'Dépôt d\'Affiliation',
    'profile.support': 'Support Technique',
    'profile.admin': 'Administration du Système',
    'profile.requestAdmin': 'Demander des privilèges d\'administrateur',
    'profile.adminRequested': 'Demande d\'administration envoyée à l\'autorité centrale.',
    'profile.current_password': 'Mot de Passe Actuel',
    'profile.new_password': 'Nouveau Mot de Passe',
    
    // Quiz/Study Page
    'quiz.question': 'Requête',
    'quiz.explanation': 'Briefing Analytique',
    'quiz.submit': 'Soumettre la Réponse',
    'quiz.next': 'Requête Suivante',
    'quiz.finish': 'Finaliser l\'Évaluation',
    'quiz.results': 'Résultat Opérationnel',
    'quiz.score': 'Score de Performance',
    'quiz.correct': 'Précis',
    'quiz.wrong': 'Imprécis',
    'quiz.time': 'Durée Temporelle',
    
    // Affiliate
    'affiliate.title': 'Terminal Partenaire',
    'affiliate.balance': 'Crédit de Commission',
    'affiliate.referrals': 'Actifs Recrutés',
    'affiliate.withdraw': 'Demander un Versement',
    'affiliate.code': 'Identifiant de Parrainage',
    'affiliate.copy': 'Copier l\'ID',
    'affiliate.history': 'Journal des Versements',
    
    // Affiliate Dashboard Expanded
    'affiliate.subtitle': 'Croissance Institutionnelle et Partages de Revenus',
    'affiliate.syncing_account': 'Synchronisation du Compte Affilié',
    'affiliate.syncing_desc': 'Engagement initial détecté. Provisionnement de vos identifiants uniques de Partenaire Diamant...',
    'affiliate.activation_required': 'Activation Requise',
    'affiliate.activation_desc': 'Rejoignez le programme de partenariat institutionnel pour générer vos identifiants de parrainage et commencer à gagner.',
    'affiliate.awaiting_auth': 'En Attente d\'Autorisation',
    'affiliate.awaiting_desc': 'Nos administrateurs vérifient actuellement votre statut institutionnel. Ce protocole se termine généralement sous 24 heures standard.',
    'affiliate.fee': 'Frais d\'Engagement',
    'affiliate.yield': 'Part de rendement',
    'affiliate.execute_activation': 'Exécuter le Protocole d\'Activation',
    'affiliate.endowment': 'Dotation Retirable',
    'affiliate.place_withdrawal': 'Placer un Retrait',
    'affiliate.payout_creds': 'Identifiants de Paiement Institutionnels',
    'affiliate.update_authority': 'Mettre à Jour l\'Autorité',
    'affiliate.init_creds': 'Initialiser les Identifiants',
    'affiliate.bank_hierarchy': 'Hiérarchie Bancaire',
    'affiliate.access_id': 'Identifiant d\'Accès',
    'affiliate.authorize_bank_desc': 'Autorisez votre compte bancaire institutionnel pour permettre la redistribution des revenus.',
    'affiliate.your_id': 'Votre Identifiant Institutionnel',
    'affiliate.sync_cache': 'Identifiant Synchronisé dans le Cache',
    'affiliate.referred_assets': 'Actifs Parrainés',
    'affiliate.total_earned': 'Total Gagné',
    'affiliate.rev_share': 'Partage de Revenus',
    'affiliate.net_balance': 'Solde Net',
    'affiliate.commission_archives': 'Archives de Commissions',
    'affiliate.enrollment': 'Inscription',
    'affiliate.direct_referral': 'Parrainage Direct',
    'affiliate.awaiting_endowment': 'En attente de votre première dotation institutionnelle',
    'affiliate.redistributions': 'Redistributions de Revenus',
    'affiliate.no_redistributed': 'Aucun revenu redistribué trouvé dans les archives',
    'affiliate.network_sync': 'Synchronisation du Réseau',
    'affiliate.verified_user': 'Utilisateur Institutionnel Vérifié',
    'affiliate.active': 'Actif',
    'affiliate.awaiting_network': 'En Attente d\'Expansion du Réseau...',
    'affiliate.payout_authority': 'Autorité de Paiement Institutionnelle',
    'affiliate.sync_creds_desc': 'Synchronisez vos identifiants bancaires pour la redistribution',
    'affiliate.financial_institution': 'Institution Financière',
    'affiliate.select_hub': 'Sélectionner le Hub Institutionnel',
    'affiliate.acc_no': 'Identifiant d\'Accès (N° de Compte)',
    'affiliate.beneficiary': 'Nom du Bénéficiaire Légal',
    'affiliate.authorize_creds': 'Autoriser les Identifiants',
    
    // Chat
    'chat.title': 'Support Institutionnel',
    'chat.boardOnline': 'Bureau d\'Archivage en Ligne',
    'chat.security': 'Sécurité : Triple Couche 256B',
    'chat.channelEstablished': 'Canal Sécurisé Établi',
    'chat.queriesSync': 'Les requêtes institutionnelles sont synchronisées ici.',
    'chat.senderAdmin': 'ArchBoard',
    'chat.placeholder': 'Interroger le support institutionnel...',
    
    // Admin Dashboard
    'admin.dashboard': 'Tableau de Bord',
    'admin.users': 'Utilisateurs',
    'admin.practice': 'Pratique Quotidienne',
    'admin.affiliates': 'Affiliés',
    'admin.withdrawals': 'Retraits',
    'admin.payments': 'Paiements',
    'admin.analytics': 'Analyses',
    'admin.departments': 'Départements',
    'admin.questions': 'Questions',
    'admin.notifications': 'Notifications',
    'admin.quotes': 'Citations',
    'admin.support': 'Support',
    'admin.settings': 'Paramètres',
    'admin.main': 'Principal',
    'admin.finance': 'Finance',
    'admin.content': 'Contenu',
    'admin.superAdmin': 'Super Administrateur',
    'admin.broadcastProtocol': 'Protocole de Diffusion',
    'admin.refreshArchives': 'Actualiser les Archives',
    'admin.overview': 'Aperçu',
    'admin.totalRevenue': 'Revenu Total',
    'admin.totalPaidOut': 'Total Payé',
    'admin.totalStudents': 'Total Étudiants',
    'admin.pendingAffiliates': 'Affiliés en Attente',
    'admin.pendingPayouts': 'Paiements en Attente',
    'admin.recentPayments': 'Paiements Récents',
    'admin.viewLedger': 'Voir le Registre',
    'admin.revenueBreakdown': 'Répartition des Revenus',
    'admin.scholarProfile': 'Profil du Boursier',
    'admin.referrer': 'Référent',
    'admin.institutionalDept': 'Dépt Institutionnel',
    'admin.affiliateStatus': 'Statut d\'Affilié',
    'admin.approvePartner': 'Approuver le Partenaire',
    'admin.role': 'Rôle',
    'admin.status': 'Statut',
    'admin.actions': 'Actions',
    'admin.export': 'Exporter',
    'admin.addUser': 'Ajouter Utilisateur',
    'admin.protocolActive': 'Protocole Global Actif',
    'admin.matrix': 'Matrice',
    'admin.registry': 'Registre',
    'admin.pendingActivations': 'Activations en Attente',
    'admin.partnerRegistry': 'Registre des Partenaires',
    'admin.refCode': 'Code de Parrainage',
    'admin.totalEarned': 'Total Gagné',
    'admin.totalPaid': 'Total Payé',
    'admin.balance': 'Solde',
    'admin.searchTransaction': 'Rechercher une référence de transaction...',
    'admin.protocolRef': 'Réf Protocole',
    'admin.scholarlyPayer': 'Payeur Érudit',
    'admin.endowment': 'Dotation',
    'admin.timestamp': 'Horodatage',
    'admin.revenueHistory': 'Historique des Revenus (Annuel)',
    'admin.payoutHistory': 'Paiements Affiliés (Annuel)',
    'admin.manifestFaculty': 'Manifester un Nouveau Département',
    'admin.facultyName': 'Nom du Département',
    'admin.systemSlug': 'Slug Système',
    'admin.tuitionBase': 'Base de Scolarité',
    'admin.operationalMode': 'Mode Opérationnel',
    'admin.editArchives': 'Modifier les Archives',
    'admin.updateFee': 'Mettre à jour les Frais',
    'admin.manifestation': 'Manifestation du Département',
    'admin.institutionalName': 'Nom Institutionnel',
    'admin.tuition': 'Scolarité',
    'admin.authorizeFaculty': 'Autoriser le Département',
    'admin.securityClearance': 'Habilitation de Sécurité',
    'admin.reviseQuery': 'Réviser la Requête d\'Archive',
    'admin.queryEntry': 'Terminal de Saisie de Requête',
    'admin.importArchive': 'Importer Archive',
    'admin.exportArchive': 'Exporter Archive',
    'admin.newQuestion': 'Ajouter une Nouvelle Question',
    'admin.explanation': 'Explication',
    'admin.confirmationDestruction': 'Confirmer la Destruction',
    'admin.initiateTransmission': 'Initier la Transmission',
    'admin.protocolHeader': 'En-tête du Protocole (Titre)',
    'admin.payload': 'Charge Utile de Transmission (Corps)',
    'admin.broadcastSecure': 'Diffuser le Protocole Sécurisé',
    'admin.historyLog': 'Journal Historique des Transmissions',
    'admin.mentalFramework': 'Journaliser le Cadre Mental',
    'admin.epistemological': 'Texte Épistémologique',
    'admin.intellectualOrigin': 'Origine Intellectuelle (Auteur)',
    'admin.publish': 'Authentifier & Publier',
    'admin.activeThreads': 'Fils Actifs',
    'admin.secureSession': 'Session sécurisée initialisée',
    
    // General / UI
    'general.back': 'Retirer',
    'general.submit': 'Soumettre l\'Autorisation',
    'general.loading': 'Traitement des Données...',
    'general.error': 'Erreur Système',
    'general.success': 'Opération Réussie',
    'general.cancel': 'Avorter',
    'general.save': 'Commiter les Changements',
    'general.edit': 'Modifier',
    'general.delete': 'Purger',
    'general.view': 'Inspecter',
    'general.search': 'Exécuter la Requête...',
    
    // Payments
    'payment.authorize': 'Autoriser le Paiement',
    'payment.currency': 'NGN',
    'payment.intl_currency': 'USD',
    'payment.unlocked': 'Accès Accordé',
    'payment.locked': 'Accès Requis',
    'payment.pay_now': 'Autoriser la Transaction',
    
    // Access
    'access.restricted': 'Accès Restreint',
    'access.restricted_desc': 'Les archives de cette faculté nécessitent une autorisation institutionnelle.',
    'access.provision': 'Fournir le Terminal d\'Accès',
    
    // Greetings
    'greet.morning': 'Bon matin',
    'greet.afternoon': 'Bon après-midi',
    'greet.evening': 'Bonsoir',
    
    // Stats
    'stats.attempted': 'Tenté',
    'stats.avg_score': 'Score Moyen',
    'stats.correct': 'Correct',
    'stats.streak': 'Série de Jours',
    
    // Actions - Quick
    'actions.study_now': 'Étudier Maintenant',
    'actions.support_admin': 'Parler à l\'Admin',
    
    // Departments (Mappings)
    'dept.Pharmacy': 'Pharmacie',
    'dept.Physiotherapy': 'Physiothérapie',
    'dept.Biomedical Laboratory Science (BMLS)': 'Science de Laboratoire Biomédical (BMLS)',
    'dept.Medicine and Surgery (MBBS)': 'Médecine et Chirurgie (MBBS)',
    'dept.Nursing': 'Soins Infirmiers'
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('app-language') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string) => {
    if (translations[language][key] !== undefined) {
      return translations[language][key];
    }
    if (key.startsWith('dept.')) {
      let clean = key.substring(5);
      while (clean.startsWith('dept.')) {
        clean = clean.substring(5);
      }
      return clean;
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
